### ISSUE TITLE
[FR] Make automatic rollover optional

### ISSUE THREAD

**Issue by barryvan** [lumoe/obsidian-rollover-daily-todos#103]
At present, the rollover happens automatically when the new day's note is created. I think it would be helpful if there were an option to disable this, such that the rollover has to be manually triggered. This would (for example) make it easier to side-step #63, as well as giving users more control over exactly when the rollover happens -- useful if, for example, one is working past midnight. :)

**Comment by komiksam** [comment]
The automatic rollover kinda ruins my editing process so I have it installed but off, and now it's became easier to check notes of previous days and move manually than to activate the plugin whenever I want to use the command (making sure it's not 23:59 or something like that). This feature would be super helpful!

**Comment by MMoMM-org** [comment]
I would like to also give a thumbsup on this. Due to timing issues with templater (after note creation I get ask questions, pull some information from the web) automatic rollover triggers to early and any changes made by it are deleted again from templater.
I did setup a button to trigger the command.. but that only really works if I don't delete the todos... which is cumbersome but necessary, as if I delete it via the plugin it would get deleted from the automatic rollover.

Easiest solution would be to make automatic rollover an on / off option.
A little bit more complicated would be an on / timed / off option.
