### ISSUE TITLE
Rollover daily todos not working from 11-Jun onwards

### ISSUE THREAD

**Issue by Shanmukha68** [lumoe/obsidian-rollover-daily-todos#105]
Hi.
rollover daily todos command was working until, 10th June. From yesterday(11th June) onwards not able to rollover the tasks. When click on 'Rollover todos' command, nothing happening, except the following message displayed in the console, but none of the todos rolled over to today's daily notes.

"rollover-daily-todos: 8 todos found in 11_Sun.md"

And no error message in console.
Further, except the option 'Delete todos from previous day', other two options were enabled. and I have not changed any settings nor installed new plugins in the past one week.

**Comment by tim-hilt** [comment]
With this kind of information, I don’t think we can provide support for you, as there was no new release drafted on the 10th of June.

Maybe you could help us out with:

- Full settings for rollover-daily-todos
- Settings for daily-notes-plugin
- A file where you can not roll over the todos

**Comment by jasontangfocus** [comment]
not working from end too. maybe caused by updates from obsidian?

**Comment by Shanmukha68** [comment]
Hi @tim-hilt,
thank you for your reply!

One more observation is, 'Rollover todos' command is triggered at the time of creating the daily notes automatically and message "rollover-daily-todos: 8 todos found in 11_Sun.md" getting printed in console. But, 'todos' are not getting rolled over. 
And when ran the 'Rollover todos' command from palette, no message is printed to console.

uploaded the settings and sample todos file as mentioned in your reply.

Full settings for rollover-daily-todos:
![RolloverTodos](https://github.com/lumoe/obsidian-rollover-daily-todos/assets/127996541/4c09089c-7585-4d61-a071-37202c4f1f86)

Settings for daily-notes-plugin:
![DailyNotes](https://github.com/lumoe/obsidian-rollover-daily-todos/assets/127996541/d2a390ee-f4ba-416c-b421-293c98d0c0c0)
A file where you can not roll over the todos:
[11_Sun.md](https://github.com/lumoe/obsidian-rollover-daily-todos/files/11728713/11_Sun.md)

**Comment by stoweboyd** [comment]
I have just installed the plugin today, and it's not doing anything in my Obsidian, either.

**Comment by alicekaerast** [comment]
I can also reproduce this issue. Creating a new daily note creates the file, adds yesterday's incomplete todos, and then deletes the todos. If I then run the rollover from the command prompt it adds yesterday's incomplete todos again, and this time they remain in place.

If I disable the Templater plugin or disable "Trigger templater on new file creation" then the todos don't get deleted. So presumably this is caused by some interaction between Templater and this plugin.

**Comment by samuelbushi** [comment]
Experiencing the same problem. After installing the plugin, there doesn't seem to be any response or changes at all to any of my tasks in the daily notes.

**Comment by ittybitBetter** [comment]
I'm having an issue with this plugin as well. The thing that's bothering me the most is that it WAS working fine yesterday. Yesterday I did a whole lot of planning and cleaning up within Obsidian and my notes and this morning with creating my new note I was sorely disappointed that my newly organized notes were not rolling over! I am completely lost on where the problem is.

I am using Periodic Notes with Daily Notes turned on, as well as yearly notes (monthly & quarterly turned off)

Here is what I've tried

- I have created tags (#) to categorize my tasks and I placed one in front of each, so I tried to remove those
- I tabbed for a new task instead of just a new line because the plugin notes say something about that
- I ran the rollover command manually
- I tried to remove the heading setting within the plugin
- I removed the children of todos setting
- I uninstalled and reinstalled the plugin
- I closed obsidian and restarted my computer
- I disabled and unchecked the Templater setting plugin as the previous post recommends

I'm lost. I don't know what else to do.

Does anyone have any recommendations?

**Comment by simonSlamka** [comment]
+1

**Comment by ittybitBetter** [comment]
Rollover worked today! I have absolutely no idea what changed, maybe there was an update?

Well, alrighty then. Until next time...

**Comment by midona** [comment]
Hi,

Glad it now works for you.  Unfortunately, it still doesn;t work for me.

The tasks get rolled over into the new daily note....then immediately
deleted.

Cheers

**Comment by lumoe** [comment]
Hi there,

I've just pushed a new release that introduces the option to disable the automatic rollover when creating the daily file.

For those utilizing the Templater plugin, ensure you turn off the automatic rollover feature within the Daily Rollover Settings tab. You can then manually roll over the to-dos via the provided command.

Currently, this approach ensures optimal compatibility and avoids potential conflicts with the Templater plugin.
