### ISSUE TITLE
Daily todos will not rollover if format includes a dynamic folder

### ISSUE THREAD

**Issue by tvdjonaswanninger** [lumoe/obsidian-rollover-daily-todos#30]
Hi,

From the documentation of the periodic notes plugin i grabbed the idea to put all my daily notes in folders which represent the calendar week. In order to do this i use this format pattern for daily notes 

`/[KW]ww/DD-MM-YYYY (dd)`

This produces files like this

KW39 (Folder)
 -  10-09-2021 (Fr)
 -  11-09-2021 (Sa)
 -  12-09-2021 (So)

But when I do this the rollover plugin does not seem to find the previous daily note. As soon as I  use the default format pattern it works again. Any idea?

**Comment by KjellConnelly** [comment]
Hi Jonas,
 
Thanks for the question :) It's because the current set of code written in this plugin looks for a flat list of daily notes, similar to how the original daily notes plugin is. Then it uses moment.js to calculate, based on filename, what date each note is for. 

After looking through the periodic notes plugin, it looks like Liam (the guy who wrote that plugin) made it look for files recursively through all sub folders as well. 

He wrote a library for handling dates, which I've already integrated into this plugin. So it would probably be somewhat easy (compared to writing the code from scratch) to integrate the functionality you were expecting. 

I've just never used sub folders for organizing my daily notes before. I have this ridiculously long list of files. So it would probably be smart to do something similar to what you're doing. 

This is fairly low on the list of things I have to do at the moment, so unless someone wants to code it themselves and issue a pull request, this might sit dormant for a few weeks or months. Most likely, I'll end up fixing it myself, but only when I end up wanting to migrate to a similar structure as yourself.

**Comment by kennyp** [comment]
Strangely this used to work for me before with Daily Notes and a dynamic path before I updated recently. :confused:

**Comment by lumoe** [comment]
This repository has been transferred to my account and is now maintained again. 

I will close this issue in favour of the newer #56. 
There also exists a fix for this feature, which I would like you to invite testing out or review the changes.
