### ISSUE TITLE
Plugin has stopped working as of the latest release

### ISSUE THREAD

**Issue by seagullmouse** [lumoe/obsidian-rollover-daily-todos#94]
Todos are not being rolled over.
- If I create today's note then the todos aren't copied across
- If I manually run the Rollover Todos Now action then nothing happens

Yesterday's note
```
## Day Plan

- [ ] Test  1
- [x] Sevgin
	- [x] PR
	- [x] Infra
- [ ] Test 2
- [x] Sam
	- [x] PRs
		- [x] Database, Doppler
	- [x] QA tests, create a task
- [ ] Test 3
```

Today's note
```
## Day Plan
```

Settings below
<img width="966" alt="image" src="https://user-images.githubusercontent.com/1561613/229119268-7adff8bb-2617-4f02-82a9-c2461fde66e2.png">

This worked until very recently, I assume it is the latest release.

**Comment by tim-hilt** [comment]
Can you share the settings for your daily-notes-plug-in?

**Comment by seagullmouse** [comment]
Great question, I think that I would have had Daily Notes configured and then added Periodic Notes later on for the weekly, yearly notes.

I've had this configured for ages now.

I've just turned off Daily Notes and recreated Today's Note and still get the same issue. (no todos rolled over, automatically or manually).

Anything else you'd like me to try?

Thanks

**Comment by seagullmouse** [comment]
I've debugged the source a bit.

If I change 
```
if (path.startsWith(`${folder}/`)) {
// to
if (path.startsWith(`${folder}`) || path.startsWith(`${folder}/`)) {
```
Then everything works perfectly.

I am not quite sure how your logic is working above around folder paths to make a PR.

**Comment by MMoMM-org** [comment]
I might have the same issue... I have enabled delete todos from previous day and those are deleted, but they aren't added to the current daily note.

**Comment by PrinceHeadache** [comment]
Hello! I'm having the same issue and have been having it since I installed this plugin about a week or two ago. The setting for deleting to-dos does function properly, but nothing rolls over to the following day. 

If you'd like me to provide some kind of information or try something to help diagnose the issue I'd be happy to give it a try. Here's my settings: 
![image](https://user-images.githubusercontent.com/126889088/230726540-6fbdf50e-d46e-454d-b12b-56d84624ac18.png)

Thanks a bunch! This plugin would be very helpful for me so I'm looking forward to using it in the future.

**Comment by tim-hilt** [comment]
Hey @PrinceHeadache and thanks for offering your help. It would in fact be very helpful to know the settings for your daily notes plugin (Daily Notes/Periodic Notes).

**Comment by PrinceHeadache** [comment]
@tim-hilt 
Sure thing! Hopefully this works: 
![image](https://user-images.githubusercontent.com/126889088/230731704-6b88b35e-4a05-4175-ad03-12b619dde3b8.png)


Thanks!

**Comment by rtsaboya** [comment]
Hello!
I am having the same problem since a few days ago. 

![image](https://user-images.githubusercontent.com/1327871/230920077-719bd48c-7b02-4fd6-93f1-0a5c4f2d79dd.png)

![image](https://user-images.githubusercontent.com/1327871/230920226-9d322565-7968-4860-a30c-39ca2b41a568.png)

**Comment by tim-hilt** [comment]
> I've debugged the source a bit.
> 
> If I change
> 
> ```
> if (path.startsWith(`${folder}/`)) {
> // to
> if (path.startsWith(`${folder}`) || path.startsWith(`${folder}/`)) {
> ```
> 
> Then everything works perfectly.
> 
> I am not quite sure how your logic is working above around folder paths to make a PR.

I'm pretty sure that was introduced by that line:

https://github.com/lumoe/obsidian-rollover-daily-todos/blob/1f20c0a758a4827ae2dd0791b62b599c8f5af4b7/src/index.js#L72

Because of that, the following logic is no longer needed:

https://github.com/lumoe/obsidian-rollover-daily-todos/blob/1f20c0a758a4827ae2dd0791b62b599c8f5af4b7/src/index.js#L108-L111

Here, we added a slash at the end of the daily-notes folder, but because of the first line I quoted, it basically checks if there are two slashes at the end, which will (hopefully) never be the case. I'll submit a PR soon and let this thread know.

If you know how to build and run an npm-project, I'd be very happy to have this tested by more than one person.

**Comment by geekbb** [comment]
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/46196358/233764786-58002ccb-c5b8-4ead-a36b-c82c5ba1d4b3.png">
<img width="787" alt="image" src="https://user-images.githubusercontent.com/46196358/233764791-cc261661-8e04-4a43-8f26-3cae105e0631.png">

I updated to 1.1.5, but it still stopped working and became invalid.

**Comment by tim-hilt** [comment]
I can’t comment on why it became invalid, but since my PR mentioned above is still not merged, there is no chance of the bug being fixed on any released version.

**Comment by MMoMM-org** [comment]
I tried the "hack" from @seagullmouse and rollover get deleted again.. but they are not added to the current daily note.

@tim-hilt did you test your merge?

**Comment by MMoMM-org** [comment]
Yes it works... but I found a new issue..

**Comment by domonnss** [comment]
hi,i met the same problem.Sometimes it works well,but sometime does not.
here my setting
![image](https://github.com/lumoe/obsidian-rollover-daily-todos/assets/60506557/ca68d94b-c18f-4805-b60e-9646852c49cb)
![image](https://github.com/lumoe/obsidian-rollover-daily-todos/assets/60506557/09acc217-8d44-4f1a-bbd4-543133533844)
have turned off the official daily notes

**Comment by tim-hilt** [comment]
@lumoe is there anything holding you back from approving #96?

**Comment by lumoe** [comment]
@all please try the newest release 1.1.6

**Comment by MSBack** [comment]
> @ALL please try the newest release 1.1.6

It works again for me after updating :)

**Comment by PrinceHeadache** [comment]
It works for me now, too. Thanks so much!
